-- DataMigration: 10 articles de blog en français, à l'état de brouillon (DRAFT), répartis sur les
-- 6 catégories du blog (cahier des charges 2026-09, §5) : Couple, Rencontre, Solitude, Mariage,
-- Communication, Vie relationnelle. Restent des brouillons tant qu'un administrateur ne les fait
-- pas avancer dans le circuit éditorial existant (IN_REVIEW -> APPROVED -> PUBLISHED).
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_22047bd3-2bd0-4431-becb-ab89ad6b3383','Speed dating à Paris : comment aborder sa première soirée sans pression','speed-dating-paris-premiere-soiree-sans-pression','Une première soirée de speed dating peut intimider. Voici comment s''y préparer pour en profiter réellement, sans jouer un rôle.','Personne ne se sent totalement à l''aise avant sa première soirée de speed dating, et c''est normal. L''idée de passer d''une table à l''autre, de se présenter en quelques minutes à des inconnus, peut sembler artificielle. Pourtant, ce format a un avantage rare : il retire la pression du "et si je ne sais pas quoi dire après le premier verre". Chaque échange a un début et une fin annoncés, ce qui libère paradoxalement la parole.

La meilleure préparation n''est pas de répéter des anecdotes calibrées, mais de clarifier pour soi-même ce que l''on cherche réellement ce soir-là : une rencontre sérieuse, une soirée agréable entre adultes qui font l''effort de se déplacer, ou simplement l''envie de sortir de sa routine. Cette clarté intérieure évite de sur-interpréter chaque échange et de rentrer chez soi épuisé d''avoir voulu plaire à tout le monde.

Sur place, quelques minutes suffisent pour sentir si une conversation coule ou si elle force. Ce n''est pas un échec si ce n''est pas le cas : c''est justement ce que permet le format, contrairement à un dîner classique où l''on reste bloqué une heure avec une personne qui ne nous convient pas. Le vrai enjeu n''est pas de "réussir" chaque table, mais de rester soi-même suffisamment pour que les bonnes rencontres puissent se reconnaître.

Un dernier point, souvent négligé : arriver dix minutes avant l''heure plutôt que pile à l''heure. Cela laisse le temps de s''installer, de perdre le stress du trajet, et d''observer le lieu avant que tout commence. Une soirée de speed dating se joue autant dans la préparation discrète que dans les échanges eux-mêmes.','Rencontre',ARRAY['speed dating','Paris','première rencontre','conseils rencontre']::text[],'Speed dating à Paris : réussir sa première soirée sans pression','Conseils concrets pour aborder une première soirée de speed dating à Paris avec sérénité, sans jouer un rôle ni se mettre trop de pression.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_a578e83e-0f85-46e0-9107-9aa37641c61a','Rencontrer quelqu''un après 35 ans : changer de méthode, pas d''exigences','rencontrer-quelquun-apres-35-ans-changer-de-methode','Après 35 ans, les rencontres se font moins souvent par hasard. Ce n''est pas une question de standards trop élevés, mais de méthode à ajuster.','Après 35 ans, on entend souvent la même remarque, bienveillante mais fausse : "tu es peut-être trop exigeant(e)". En réalité, le problème est rarement le niveau d''exigence — c''est le nombre d''occasions de rencontre qui a mécaniquement diminué. Les études, les stages, les colocations qui produisaient des rencontres presque par accident appartiennent souvent au passé. Le cercle social se stabilise, les soirées se raréfient, et les rencontres nouvelles ne se produisent plus toutes seules.

Ce constat n''est pas un problème de personnalité, c''est un problème de fréquence d''exposition à de nouvelles personnes compatibles. La solution n''est donc pas d''assouplir ses critères, mais de recréer artificiellement ce que le hasard ne produit plus : des occasions régulières, dans un cadre où d''autres personnes cherchent, elles aussi, une rencontre sincère plutôt qu''une distraction du soir.

C''est précisément ce que permettent des formats comme les soirées à thème ou le speed dating organisé : ils remplacent le hasard social par une intention explicite, partagée par tout le monde dans la salle. Personne n''est là par accident, ce qui change immédiatement la nature des échanges — plus directs, plus vrais, moins soumis au jeu de la séduction excessive.

Il ne s''agit pas de revoir ses attentes à la baisse, mais d''accepter que la rencontre, après un certain âge, redevient une démarche active plutôt qu''un heureux hasard. C''est une bonne nouvelle : une démarche active se travaille, alors qu''un hasard ne se force pas.','Rencontre',ARRAY['rencontre après 35 ans','célibat','rencontre sérieuse','vie amoureuse adulte']::text[],'Rencontrer quelqu''un après 35 ans : la méthode plutôt que les exigences','Pourquoi les rencontres se raréfient après 35 ans et comment recréer, par une démarche active, les occasions que le hasard n''offre plus.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_39b3dbf4-7533-4540-be11-de6e10704c24','Raviver la complicité dans un couple installé','raviver-complicite-couple-installe','La routine n''est pas l''ennemie du couple. C''est l''absence de nouveauté partagée qui use la complicité, bien plus que le temps qui passe.','On accuse souvent "la routine" d''éroder les couples installés depuis plusieurs années. Le vrai coupable est plus précis : ce n''est pas la répétition du quotidien qui use la complicité, c''est l''absence de nouveauté vécue à deux. Un couple peut traverser dix ans de rituels stables et rester très proche, tant qu''il continue, régulièrement, à vivre ensemble quelque chose qu''il n''a jamais vécu avant.

La complicité se nourrit d''expériences partagées qui sortent légèrement de la zone connue : un lieu jamais visité, une activité jamais tentée à deux, une conversation qui aborde un sujet qu''on n''avait jamais pris le temps d''ouvrir. Ce n''est pas la nouveauté spectaculaire qui compte, mais la nouveauté suffisante pour que les deux personnes redécouvrent, l''une chez l''autre, une réaction ou une facette inattendue.

C''est là que beaucoup de couples se trompent de solution : ils cherchent à "sauver" la relation par de grandes décisions (voyage exceptionnel, projet de vie) alors que la complicité se répare surtout par petites touches régulières. Une soirée différente une fois par mois entretient bien plus la relation qu''un unique week-end organisé une fois par an et jamais renouvelé.

Sortir ensemble dans un cadre nouveau — une soirée à thème, un événement organisé autour d''une activité partagée — a cet avantage discret : cela oblige les deux personnes à interagir hors de leurs rôles habituels à la maison. On se redécouvre un peu, sans grand discours sur "le couple", simplement en vivant ensemble un moment qui n''existait pas avant.','Couple',ARRAY['couple installé','complicité','routine couple','sortie en couple']::text[],'Raviver la complicité dans un couple installé','Ce n''est pas le temps qui use la complicité d''un couple, mais l''absence de nouveauté partagée. Comment la faire revenir sans grand bouleversement.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_23dbdf2c-1b32-4b1b-9e0e-061bbcdf498c','Sortir en couple : pourquoi continuer à multiplier les premières fois','sortir-en-couple-multiplier-premieres-fois','Les couples heureux sur la durée ne sont pas ceux qui évitent la routine, mais ceux qui continuent à s''offrir de vraies premières fois.','Il existe une différence discrète mais décisive entre les couples qui s''essoufflent et ceux qui durent en restant vivants : les seconds continuent, année après année, à s''offrir de vraies premières fois. Premier restaurant jamais testé, premier week-end dans une ville inconnue, première soirée à un type d''événement jamais fréquenté ensemble. Ce n''est pas une question de budget ou de temps libre, c''est une priorité qu''on décide de garder.

La raison est simple : une première fois oblige à réagir dans l''instant, sans script déjà écrit par les habitudes. On observe alors son partenaire réagir à quelque chose de neuf, on découvre une réaction, un enthousiasme ou une pudeur qu''on ne connaissait pas encore complètement. C''est cette petite dose de surprise, répétée régulièrement, qui empêche une relation de se figer dans un rôle appris par cœur.

Beaucoup de couples remettent ces premières fois à "quand on aura plus de temps", et cette liste d''attente ne se vide jamais. La solution la plus efficace n''est pas d''attendre le moment idéal, mais de se fixer un rythme volontaire : une sortie réellement nouvelle toutes les quelques semaines, même modeste, plutôt qu''un grand projet sans cesse repoussé.

Participer ensemble à une soirée organisée autour d''un thème que l''on n''a jamais essayé — networking convivial, dégustation, activité collective — fonctionne particulièrement bien pour cela : le cadre est déjà pensé pour créer de l''interaction, il ne reste plus qu''à s''y présenter à deux et à se laisser surprendre, ensemble.','Couple',ARRAY['couple','sortie de couple','vie de couple','nouveauté en couple']::text[],'Sortir en couple : l''importance de multiplier les premières fois','Les couples qui durent sont ceux qui continuent à s''offrir de vraies premières fois. Comment garder cette habitude sans attendre le moment parfait.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_9cd7afab-2a3d-415e-9be1-381dd627a114','Sortir de la solitude choisie : le premier pas compte plus que le bon pas','sortir-solitude-choisie-premier-pas','La solitude choisie devient parfois une solitude subie sans qu''on s''en rende compte. En sortir demande moins de plan parfait que de premier geste.','Il y a une solitude que l''on choisit vraiment — un besoin de calme, de récupération, une saison de vie — et il y a la solitude qui s''installe sans qu''on l''ait vraiment décidée, simplement parce qu''on a cessé de faire l''effort de sortir. La différence entre les deux se voit à une question simple : si l''occasion se présentait ce soir, en aurait-on envie ? Quand la réponse honnête est oui mais qu''on ne fait jamais le premier pas, ce n''est plus un choix, c''est une inertie.

Le piège de cette inertie, c''est qu''elle demande de moins en moins d''énergie chaque jour qu''on la laisse s''installer, alors que le premier pas pour en sortir demande, lui, toujours le même effort ponctuel. C''est pour cela que la plupart des tentatives de "reprendre une vie sociale" échouent : on attend le moment où l''on se sentira enfin prêt, motivé, disponible — et ce moment n''arrive jamais tout seul.

La solution la plus fiable n''est pas de trouver la motivation parfaite, mais de réduire au minimum la décision à prendre. S''inscrire à un événement précis, à une date précise, avec une heure de début et de fin annoncée, transforme "je devrais sortir plus" (une intention vague, jamais suivie) en "j''ai un rendez-vous jeudi à 19h" (un fait concret, difficile à annuler sans y penser deux fois).

Ce n''est pas la qualité de la première sortie qui compte le plus, contrairement à ce qu''on imagine. Une soirée moyenne, mais qui a effectivement eu lieu, fait plus progresser que la sortie parfaite qu''on continue de repousser en attendant d''être prêt.','Solitude',ARRAY['solitude','sortir de la solitude','vie sociale','isolement']::text[],'Sortir de la solitude choisie : pourquoi le premier pas compte plus que le bon pas','La solitude choisie glisse parfois vers l''isolement sans qu''on le décide. Voici pourquoi agir compte plus que trouver le moment ou le plan parfait.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_8fa2effd-136b-4b7c-bc71-75225902a262','Vivre seul sans être isolé : reconstruire un réseau social après une rupture','vivre-seul-sans-isolement-reseau-apres-rupture','Une rupture réduit souvent le cercle social bien plus que prévu. Le reconstruire est une démarche active, pas une conséquence automatique du temps.','Après une rupture, on sous-estime presque toujours à quel point le cercle social se rétrécit en même temps que le couple se termine. Des amitiés communes s''effacent par gêne, des habitudes de sortie disparaissent avec l''ex-partenaire qui les organisait, et l''on se retrouve, souvent sans l''avoir anticipé, avec beaucoup moins d''occasions de voir du monde qu''avant la relation.

Le réflexe naturel est d''attendre que "le temps fasse son travail" et que la vie sociale reprenne naturellement sa place. En pratique, cela se produit rarement seul : un cercle social qui s''est réduit ne se reconstruit pas par magie, il se reconstruit par des décisions actives, répétées, même lorsque l''énergie ou l''envie n''est pas encore complètement revenue.

La bonne nouvelle, c''est que cette reconstruction ne demande pas de refaire immédiatement l''histoire d''une amitié de dix ans. Elle commence par des interactions plus légères et plus fréquentes : un événement, une activité collective, un lieu où l''on croise régulièrement les mêmes têtes sans enjeu affectif immédiat. C''est cette régularité, plus que l''intensité d''un seul événement réussi, qui recrée progressivement un sentiment d''appartenance.

Il n''est pas nécessaire, à ce stade, de chercher une nouvelle relation amoureuse. Se reconstruire un réseau social — des connaissances, des habitudes de sortie, des visages familiers — est souvent la première étape qui rend tout le reste plus facile, y compris, plus tard, une nouvelle rencontre.','Solitude',ARRAY['rupture','réseau social','reconstruction après rupture','isolement']::text[],'Vivre seul sans être isolé : reconstruire son réseau social après une rupture','Une rupture réduit souvent le cercle social plus qu''on ne le pense. Comment le reconstruire activement plutôt que d''attendre que le temps s''en charge.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_820aef15-ef61-46a5-8854-fc264080fcc8','Avant le mariage : les questions à se poser à deux, pas seulement pour la fête','avant-le-mariage-questions-a-se-poser-a-deux','L''organisation d''un mariage occupe souvent tout l''espace mental, au point d''éclipser les vraies questions de couple qu''il vaudrait mieux poser avant.','L''organisation d''un mariage prend une place démesurée dans les mois qui précèdent la cérémonie : traiteur, liste d''invités, lieu, tenue. Ces décisions sont légitimes, mais elles occupent souvent tellement d''espace mental qu''elles finissent par remplacer des conversations plus essentielles, celles qui concernent la vie à deux une fois la fête terminée.

Les couples qui abordent le mariage avec le plus de sérénité sont rarement ceux qui ont organisé la fête la plus impressionnante. Ce sont ceux qui ont pris le temps, avant le grand jour, d''aligner leurs attentes sur des sujets peu glamour mais structurants : la répartition des décisions financières, la place respective des deux familles, la vision partagée — ou non — d''un projet d''enfants, la gestion des désaccords une fois l''euphorie de la préparation retombée.

Ces conversations sont parfois évitées précisément parce que la période du mariage est censée être joyeuse, et qu''aborder des désaccords potentiels semble déplacé. C''est pourtant le moment le plus adapté pour les avoir : les deux personnes s''engagent volontairement dans une décision de long terme, ce qui rend la discussion plus constructive qu''à un moment de tension ordinaire.

Un mariage réussi ne se mesure pas à la qualité de la soirée, mais à la clarté avec laquelle les deux personnes savent, en sortant de la cérémonie, ce qu''elles viennent réellement de décider ensemble — au-delà de la fête elle-même.','Mariage',ARRAY['mariage','avant le mariage','préparation mariage','couple engagement']::text[],'Avant le mariage : les vraies questions à se poser à deux','Au-delà de l''organisation de la fête, les couples qui abordent le mariage le plus sereinement sont ceux qui ont d''abord aligné leurs attentes de fond.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_8109c706-45df-43e9-9ef9-fbfa96d48f6d','Écoute active : la compétence la plus sous-estimée d''un premier rendez-vous','ecoute-active-competence-sous-estimee-premier-rendez-vous','On prépare souvent un premier rendez-vous en pensant à ce qu''on va dire. La vraie différence se joue le plus souvent dans la manière d''écouter.','Avant un premier rendez-vous, la plupart des gens se demandent surtout quoi dire : quelles anecdotes raconter, comment se présenter sous son meilleur jour, quels sujets éviter. Cette préparation, bien qu''utile, laisse de côté la compétence qui fait réellement la différence sur le moment : la qualité de l''écoute.

L''écoute active ne consiste pas simplement à se taire pendant que l''autre parle. C''est une attention qui se voit : reformuler brièvement ce qu''on vient d''entendre, poser une question qui prolonge ce que la personne a dit plutôt que de rebondir sur un sujet totalement différent, laisser un silence exister sans se précipiter pour le remplir. Ces gestes, minimes en apparence, créent un sentiment d''être réellement entendu — beaucoup plus rare, et donc beaucoup plus mémorable, qu''un enchaînement de bonnes histoires.

Beaucoup de premiers rendez-vous ratés ne sont pas ratés parce que l''un des deux manquait d''intérêt objectivement, mais parce que chacun attendait son tour de parler plutôt que d''écouter vraiment l''autre. La conversation ressemble alors à deux monologues parallèles plutôt qu''à un vrai échange, et cette sensation, même diffuse, laisse une impression de rendez-vous "qui n''a pas pris".

La bonne nouvelle est que l''écoute active se travaille bien plus facilement que le charisme ou l''humour, souvent perçus comme innés. Il suffit de ralentir volontairement son propre rythme de parole et de résister à l''envie de préparer sa réponse pendant que l''autre parle encore.','Communication',ARRAY['communication','premier rendez-vous','écoute active','conversation']::text[],'Écoute active : la compétence sous-estimée d''un premier rendez-vous','La réussite d''un premier rendez-vous dépend souvent plus de la qualité de l''écoute que du contenu de la conversation. Comment la pratiquer concrètement.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_76ab6e76-63f1-4725-bde3-e7bb4d2d0f52','Dire non sans blesser : poser ses limites dès les premiers échanges','dire-non-sans-blesser-poser-ses-limites','Poser une limite dès le début d''une relation naissante n''est pas un manque de délicatesse. C''est souvent ce qui évite les malentendus les plus douloureux.','Dans les premières semaines d''une relation naissante, beaucoup de personnes évitent de poser une limite claire par peur de paraître froides ou de gâcher une ambiance encore fragile. Ce silence, pourtant bien intentionné, produit souvent l''effet inverse : les malentendus qui n''ont pas été clarifiés tôt reviennent presque toujours, plus tard, sous une forme plus douloureuse.

Dire non — à une sortie que l''on ne souhaite pas encore, à un rythme de messages trop rapide, à une question trop intime posée trop vite — n''est pas un rejet de la personne. C''est une information utile, donnée au bon moment, qui permet à l''autre d''ajuster son comportement sans avoir à le deviner. La plupart des personnes préfèrent, une fois la surprise passée, une limite clairement énoncée à un flou permanent qui les laisse dans l''incertitude.

La manière de le dire compte davantage que le fait de le dire. Une limite posée avec calme, sans justification excessive ni agressivité — "je préfère qu''on garde ce rythme pour l''instant" plutôt qu''un silence gêné ou une excuse inventée — se reçoit généralement beaucoup mieux qu''on ne l''imagine à l''avance.

Les débuts de relation où les deux personnes osent, progressivement, dire ce qui leur convient ou non, ont statistiquement plus de chances de durer que ceux où chacun tente de deviner les attentes de l''autre sans jamais les vérifier à voix haute.','Communication',ARRAY['limites relationnelles','communication','début de relation','affirmation de soi']::text[],'Dire non sans blesser : poser ses limites dès les premiers échanges','Poser une limite claire dès le début d''une relation naissante évite la plupart des malentendus. Comment le faire sans agressivité ni excuse inutile.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","status","aiGenerated","createdAt","updatedAt") VALUES ('article_f312dfca-497d-4364-a912-3588de088c97','Rythme relationnel : pourquoi il n''y a pas de bon tempo universel','rythme-relationnel-pas-de-bon-tempo-universel','Certains couples se disent ''je t''aime'' au bout de trois semaines, d''autres au bout de six mois. Le rythme d''une relation n''a pas de norme fiable.','Il existe une pression sociale discrète mais persistante autour du "bon rythme" d''une relation : à quel moment officialiser, quand présenter l''autre à ses proches, à partir de combien de mois une relation est censée être "sérieuse". Ces repères, largement diffusés par les récits collectifs et les comparaisons entre amis, donnent l''illusion qu''il existerait un tempo universel à respecter.

En réalité, le rythme d''une relation dépend d''un nombre de facteurs bien trop personnels pour être comparé d''un couple à l''autre : le passé affectif de chacun, la disponibilité émotionnelle du moment, les rythmes de vie professionnels, ou simplement des tempéraments différents face à l''engagement. Deux relations qui avancent à des vitesses très différentes peuvent être, l''une comme l''autre, parfaitement saines.

Le vrai risque n''est pas d''avancer "trop lentement" ou "trop vite" par rapport à une norme extérieure. C''est le décalage non exprimé entre les deux personnes concernées : l''une pressée par la comparaison sociale, l''autre suivant son propre tempo sans le dire clairement. C''est ce silence, plus que la vitesse elle-même, qui crée de la frustration ou de l''incompréhension.

La question à se poser n''est donc pas "sommes-nous dans les temps", mais "sommes-nous d''accord, tous les deux, sur le rythme que nous vivons actuellement". Une relation qui avance lentement mais en accord mutuel est en meilleure santé qu''une relation rapide où l''un des deux suit, en silence, un rythme qui n''est pas vraiment le sien.','Vie relationnelle',ARRAY['vie relationnelle','rythme de couple','engagement','relation amoureuse']::text[],'Rythme relationnel : pourquoi il n''existe pas de bon tempo universel','Il n''y a pas de norme fiable pour le rythme d''une relation. Ce qui compte réellement, c''est l''accord mutuel entre les deux personnes sur leur propre tempo.','DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);