-- DataMigration: ordre correctif 2026-09-20 (C28) — les 10 articles doivent être visibles
-- ensemble en brouillon dans l'admin de développement dès maintenant, sans attendre une
-- libération quotidienne réservée à la production. Fait sortir les 9 restants de la réserve
-- ArticleQueueEntry vers Article (statut DRAFT) et réinitialise ArticleQueueState : la file
-- 1/jour reste dans le code pour les FUTURS articles écrits après la mise en production,
-- mais ne doit plus retenir l'inventaire déjà rédigé et attendu en relecture immédiate.
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgmo00009k1vv2ilxz3h';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgn400019k1v483pfq2g';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgnb00029k1vtabkqe13';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgnh00039k1vl8kba5i2';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgnm00049k1vc51c9zvc';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgnr00059k1vihtpms0g';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgnz00069k1v0oozqgwh';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgo500079k1v9kl459iu';
INSERT INTO "Article" ("id","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","status","aiGenerated","createdAt","updatedAt") SELECT gen_random_uuid()::text, "title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl",'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "ArticleQueueEntry" WHERE "id" = 'cmua0dgob00089k1vsn20q7ar';
DELETE FROM "ArticleQueueEntry" WHERE "id" IN ('cmua0dgmo00009k1vv2ilxz3h','cmua0dgn400019k1v483pfq2g','cmua0dgnb00029k1vtabkqe13','cmua0dgnh00039k1vl8kba5i2','cmua0dgnm00049k1vc51c9zvc','cmua0dgnr00059k1vihtpms0g','cmua0dgnz00069k1v0oozqgwh','cmua0dgo500079k1v9kl459iu','cmua0dgob00089k1vsn20q7ar');
UPDATE "ArticleQueueState" SET "lastReleasedAt" = NULL WHERE "id" = 'singleton';