import { createContext, FormEvent, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import type { PublicEvent, SessionUser } from "@nour/shared";
import { api, getToken, setToken } from "./api";

type AuthState = { user: (SessionUser & {profile?: any}) | null; loading: boolean; refresh: () => Promise<void>; logout: () => void };
const AuthContext = createContext<AuthState>(null as never);
const useAuth = () => useContext(AuthContext);

const money = (cents: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(cents / 100);
const dateTime = (value: string) => new Intl.DateTimeFormat("fr-FR", { weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthState["user"]>(null); const [loading, setLoading] = useState(true);
  const refresh = async () => { if (!getToken()) { setUser(null); setLoading(false); return; } try { setUser(await api("/me")); } catch { setToken(null); setUser(null); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  return <AuthContext.Provider value={{ user, loading, refresh, logout: () => { setToken(null); setUser(null); } }}>{children}</AuthContext.Provider>;
}

function Logo() { return <Link className="logo" to="/"><span>N</span><strong>NŪR <b>MEET</b></strong></Link>; }
function Header() {
  const { user, logout } = useAuth();
  return <header className="site-header"><Logo/><nav><NavLink to="/">Accueil</NavLink><NavLink to="/events">Événements</NavLink>{user && <NavLink to="/dashboard">Mon espace</NavLink>}{user && ["ADMIN","ORGANIZER","MODERATOR","RECEPTION"].includes(user.role) && <NavLink to="/admin">Administration</NavLink>}</nav><div className="header-actions">{user ? <><span className="member-name">{user.displayName}</span><button className="link-button" onClick={logout}>Déconnexion</button></> : <Link className="button small" to="/login">Se connecter</Link>}</div></header>;
}
function Layout({ children }: {children: ReactNode}) { return <><Header/><main>{children}</main><footer><Logo/><p>Paris et Île-de-France · Expérience privée · Données protégées</p></footer></>; }
function Loading() { return <div className="state-page"><div className="spinner"/><h2>Chargement…</h2></div>; }
function Notice({ kind="info", children }: {kind?: "info"|"error"|"success", children: ReactNode}) { return <div className={`notice ${kind}`}>{children}</div>; }
function Protected({ children, roles }: {children: ReactNode; roles?: string[]}) { const {user,loading}=useAuth(); if(loading)return <Loading/>; if(!user)return <Navigate to="/login" replace/>; if(roles&&!roles.includes(user.role))return <Navigate to="/dashboard" replace/>; return <>{children}</>; }

function EventCard({ event }: {event: PublicEvent}) {
  const full=event.confirmedCount>=event.capacity;
  return <article className="event-card"><div className="event-art"><span>{event.category.toUpperCase()}</span><i/></div><div className="event-copy"><small>{dateTime(event.startsAt).toUpperCase()}</small><h3>{event.title}</h3><p>{event.district} · {full?"Complet":`${event.capacity-event.confirmedCount} places restantes`}</p><div><strong>{money(event.priceCents)}</strong><Link to={`/events/${event.slug}`}>Découvrir →</Link></div></div></article>;
}
function Home() {
  const [events,setEvents]=useState<PublicEvent[]>([]); useEffect(()=>{api<PublicEvent[]>("/events").then(setEvents).catch(()=>{})},[]);
  return <Layout><section className="hero"><div><span className="eyebrow">PARIS · ÎLE-DE-FRANCE</span><h1>Des rencontres<br/><em>qui comptent.</em></h1><p>Des événements élégants et confidentiels, pensés pour créer de vraies connexions dans un cadre respectueux.</p><div className="hero-actions"><Link className="button" to="/events">Voir les événements</Link><a className="button secondary" href="#concept">Découvrir le concept</a></div><div className="trust"><span>✓ Profils sélectionnés</span><span>✓ Lieux premium</span><span>✓ Cadre confidentiel</span></div></div><div className="hero-art"><div className="arch"><span>ن</span></div><div className="next-card"><div className="avatar">SM</div><div><small>PROCHAINE SOIRÉE</small><strong>{events[0]?.title??"Dîner & Connexions"}</strong><span>{events[0]?dateTime(events[0].startsAt):"Samedi · Paris"}</span></div></div></div></section><section className="metrics"><div><strong>420+</strong><span>Membres validés</span></div><div><strong>36</strong><span>Événements organisés</span></div><div><strong>4,8/5</strong><span>Satisfaction</span></div></section><section id="concept" className="section"><div className="section-title"><span className="eyebrow">LE CONCEPT</span><h2>Du réel au numérique, avec votre consentement.</h2></div><div className="feature-grid"><div><b>01</b><h3>Candidature</h3><p>Chaque nouveau membre complète son profil et réserve un court appel.</p></div><div><b>02</b><h3>Rencontre</h3><p>Les événements réunissent 20 à 40 personnes dans un cadre privé.</p></div><div><b>03</b><h3>Contact choisi</h3><p>Un code personnel permet d’envoyer une demande. Le chat s’ouvre après acceptation.</p></div></div></section>{events.length>0&&<section className="section"><div className="section-title row"><div><span className="eyebrow">À VENIR</span><h2>Les prochaines rencontres</h2></div><Link to="/events">Tout afficher →</Link></div><div className="event-grid">{events.slice(0,3).map(e=><EventCard key={e.id} event={e}/>)}</div></section>}</Layout>;
}

function Events() {
  const [events,setEvents]=useState<PublicEvent[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("");
  useEffect(()=>{api<PublicEvent[]>(`/events?${new URLSearchParams({...(q?{q}:{}),...(category?{category}:{})})}`).then(setEvents)},[q,category]);
  return <Layout><section className="page"><span className="eyebrow">CALENDRIER</span><h1>Trouvez la rencontre qui vous ressemble.</h1><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher un événement"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Toutes les catégories</option><option>Rencontres</option><option>Networking</option><option>Culture</option></select></div>{events.length?<div className="event-grid">{events.map(e=><EventCard key={e.id} event={e}/>)}</div>:<div className="empty"><span>◇</span><h2>Aucun événement disponible</h2><p>Modifiez vos filtres ou revenez prochainement.</p></div>}</section></Layout>;
}

function EventDetail() {
  const {id}=useParams(); const {user}=useAuth(); const [event,setEvent]=useState<PublicEvent|null>(null),[motivation,setMotivation]=useState(""),[application,setApplication]=useState<any>(null),[slots,setSlots]=useState<any[]>([]),[message,setMessage]=useState("");
  useEffect(()=>{api<PublicEvent>(`/events/${id}`).then(setEvent)},[id]);
  if(!event)return <Layout><Loading/></Layout>;
  const apply=async(e:FormEvent)=>{e.preventDefault();setMessage("");try{const a=await api<any>(`/events/${event.id}/apply`,{method:"POST",body:JSON.stringify({motivation})});setApplication(a);setSlots(await api(`/events/${event.id}/call-slots`));}catch(err){setMessage((err as Error).message)}};
  const schedule=async(slotId:string)=>{await api(`/applications/${application.id}/schedule`,{method:"POST",body:JSON.stringify({slotId})});setMessage("Votre entretien est confirmé. Un rappel a été créé.");setApplication(null)};
  const full=event.confirmedCount>=event.capacity;
  return <Layout><section className="event-hero"><span className="eyebrow">{event.category.toUpperCase()}</span><h1>{event.title}</h1><p>{event.description}</p><div className="rings"/></section><section className="event-layout"><article><div className="facts"><div><small>DATE</small><b>{dateTime(event.startsAt)}</b></div><div><small>LIEU</small><b>{event.district}</b></div><div><small>CAPACITÉ</small><b>{event.capacity} participants</b></div></div><h2>Une expérience pensée pour de vraies rencontres</h2><p>Accueil personnalisé, animation légère, temps libres et respect de la confidentialité. Une boisson est incluse avec le billet.</p><ul><li>Profils sélectionnés</li><li>QR code d’entrée unique</li><li>Code de contact privé</li><li>Équipe présente sur place</li></ul></article><aside className="booking"><small>À PARTIR DE</small><strong>{money(event.priceCents)}</strong><div><span>Disponibilité</span><b>{full?"Complet":`${event.capacity-event.confirmedCount} places`}</b></div>{message&&<Notice kind={message.includes("confirmé")?"success":"error"}>{message}</Notice>}{!user?<Link className="button full" to="/login">Se connecter pour candidater</Link>:full?<button className="button full" onClick={()=>api(`/events/${event.id}/waitlist`,{method:"POST"}).then(()=>setMessage("Vous êtes inscrit sur la liste d’attente."))}>Rejoindre la liste d’attente</button>:application?<div className="slot-list"><h3>Choisissez votre appel</h3>{slots.map(s=><button key={s.id} onClick={()=>schedule(s.id)}>{dateTime(s.startsAt)}</button>)}</div>:<form onSubmit={apply}><label>Votre motivation<textarea required minLength={30} value={motivation} onChange={e=>setMotivation(e.target.value)} placeholder="Expliquez en quelques lignes ce que vous recherchez…"/></label><button className="button full">Envoyer ma candidature</button></form>}<p className="fine">Le paiement est proposé uniquement après acceptation.</p></aside></section></Layout>;
}

function Login() {
  const [phone,setPhone]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<1|2>(1),[error,setError]=useState(""),[devCode,setDevCode]=useState<string|null>(null); const {refresh}=useAuth(); const navigate=useNavigate();
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");try{if(step===1){const result=await api<{delivery:"mock"|"sms";devCode?:string}>("/auth/request-otp",{method:"POST",body:JSON.stringify({phone})});setDevCode(result.devCode??null);setStep(2)}else{const result=await api<{token:string}>("/auth/verify-otp",{method:"POST",body:JSON.stringify({phone,code})});setToken(result.token);await refresh();navigate("/dashboard")}}catch(err){setError((err as Error).message)}};
  return <Layout><section className="auth-page"><div className="auth-visual"><blockquote>« Une belle rencontre commence par un cadre de confiance. »</blockquote></div><form className="auth-form" onSubmit={submit}><span className="eyebrow">CONNEXION SÉCURISÉE</span><h1>{step===1?"Votre numéro ouvre la porte.":"Entrez le code reçu."}</h1><p>{step===1?"Aucun mot de passe à mémoriser.":`Code envoyé au ${phone}`}</p>{error&&<Notice kind="error">{error}</Notice>}{step===1?<label>Numéro de téléphone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+33612345678" autoComplete="tel" inputMode="tel" required/></label>:<label>Code à six chiffres<input className="otp-input" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="••••••" autoComplete="one-time-code" inputMode="numeric" required/></label>}<button className="button full">{step===1?"Recevoir mon code":"Vérifier le code"}</button>{devCode&&<div className="demo-box"><b>Mode local — aucun SMS facturé</b><span>Code de développement : {devCode}</span></div>}</form></section></Layout>;
}

function ProfileEditor({onSaved}:{onSaved:()=>void}) {
  const {user}=useAuth(); const [form,setForm]=useState({displayName:user?.displayName??"",email:user?.email??"",birthDate:"1992-06-14",city:user?.profile?.city??"",profession:user?.profile?.profession??"",interests:(user?.profile?.interests??[]).join(", "),bio:user?.profile?.bio??""});const [message,setMessage]=useState("");
  const save=async(e:FormEvent)=>{e.preventDefault();await api("/me/profile",{method:"PATCH",body:JSON.stringify({...form,email:form.email||null,interests:form.interests.split(",").map((x:string)=>x.trim()).filter(Boolean)})});setMessage("Profil enregistré.");onSaved()};
  return <form className="panel form-grid" onSubmit={save}><div className="panel-title"><h2>Mon profil</h2><span>Informations privées</span></div>{message&&<Notice kind="success">{message}</Notice>}<label>Prénom ou pseudonyme<input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Date de naissance<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})}/></label><label>Ville<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Profession<input value={form.profession} onChange={e=>setForm({...form,profession:e.target.value})}/></label><label>Centres d’intérêt<input value={form.interests} onChange={e=>setForm({...form,interests:e.target.value})}/></label><label className="wide">Biographie<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><button className="button">Enregistrer</button></form>;
}

function Dashboard() {
  const {user,refresh}=useAuth(); const [apps,setApps]=useState<any[]>([]),[tickets,setTickets]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[tab,setTab]=useState("reservations"),[paying,setPaying]=useState<string|null>(null),[message,setMessage]=useState("");
  const load=()=>Promise.all([api<any[]>("/me/applications"),api<any[]>("/me/tickets"),api<any[]>("/notifications")]).then(([a,t,n])=>{setApps(a);setTickets(t);setNotifications(n)}); useEffect(()=>{load()},[]);
  const pay=async(id:string)=>{setPaying(id);try{await api(`/checkout/${id}`,{method:"POST",body:JSON.stringify({cardNumber:"4242424242424242"})});setMessage("Paiement de test confirmé. Votre billet est prêt.");await load()}catch(e){setMessage((e as Error).message)}finally{setPaying(null)}};
  return <Layout><section className="dashboard-shell"><aside><div className="profile-card"><div className="avatar large">{user?.displayName?.slice(0,2).toUpperCase()}</div><h3>{user?.displayName}</h3><span>{user?.profile?.validatedAt?"Profil validé":"Profil à compléter"}</span></div>{[["reservations","Réservations"],["tickets","Billets"],["profile","Profil"],["notifications","Notifications"],["contacts","Contacts et messages"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}<span>›</span></button>)}</aside><div className="dashboard-content"><span className="eyebrow">ESPACE PARTICIPANT</span><h1>{tab==="reservations"?"Mes événements":tab==="tickets"?"Mes billets":tab==="profile"?"Mon profil":tab==="notifications"?"Notifications":"Contacts et messages"}</h1>{message&&<Notice kind={message.includes("confirmé")?"success":"error"}>{message}</Notice>}{tab==="reservations"&&<div className="stack">{apps.map(a=><article className="reservation" key={a.id}><div className="date-box"><strong>{new Date(a.event.startsAt).getDate()}</strong><span>{new Date(a.event.startsAt).toLocaleString("fr-FR",{month:"short"}).toUpperCase()}</span></div><div><small>{a.status.replaceAll("_"," ")}</small><h3>{a.event.title}</h3><p>{dateTime(a.event.startsAt)} · {a.event.district}</p></div>{a.status==="PAYMENT_PENDING"&&a.reservation&&<button className="button" disabled={paying===a.reservation.id} onClick={()=>pay(a.reservation.id)}>{paying?"Paiement…":`Payer ${money(a.event.priceCents)}`}</button>}</article>)}</div>}{tab==="tickets"&&<div className="ticket-grid">{tickets.map(t=><article className="ticket" key={t.id}><div><span className="eyebrow">{new Date(t.reservation.event.startsAt).toLocaleDateString("fr-FR")}</span><h2>{t.reservation.event.title}</h2><p>{t.reservation.event.district}</p></div><img src={t.qrDataUrl} alt={`QR code du billet ${t.code}`}/><b>{t.code}</b></article>)}</div>}{tab==="profile"&&<ProfileEditor onSaved={refresh}/>} {tab==="notifications"&&<div className="stack">{notifications.map(n=><article className="notification" key={n.id}><i/><div><h3>{n.title}</h3><p>{n.body}</p><small>{dateTime(n.createdAt)}</small></div></article>)}</div>}{tab==="contacts"&&<Messages/>}</div></section></Layout>;
}

function Messages() {
  const [conversations,setConversations]=useState<any[]>([]),[active,setActive]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[body,setBody]=useState(""); const {user}=useAuth();
  useEffect(()=>{api<any[]>("/conversations").then(c=>{setConversations(c);if(c[0])open(c[0])})},[]);
  const open=async(c:any)=>{setActive(c);setMessages(await api(`/conversations/${c.id}/messages`))};
  const send=async(e:FormEvent)=>{e.preventDefault();if(!body.trim())return;const m=await api<any>(`/conversations/${active.id}/messages`,{method:"POST",body:JSON.stringify({body})});setMessages([...messages,m]);setBody("")};
  const other=(c:any)=>c.members.find((m:any)=>m.userId!==user?.id)?.user;
  return <div className="messages"><aside>{conversations.map(c=><button key={c.id} className={active?.id===c.id?"active":""} onClick={()=>open(c)}><div className="avatar">{other(c)?.displayName.slice(0,2).toUpperCase()}</div><div><b>{other(c)?.displayName}</b><span>{c.messages[0]?.body??"Nouvelle conversation"}</span></div></button>)}</aside><section>{active?<><div className="chat-head"><div className="avatar">{other(active)?.displayName.slice(0,2).toUpperCase()}</div><div><b>{other(active)?.displayName}</b><span>Contact accepté</span></div></div><div className="chat-body">{messages.map(m=><div key={m.id} className={`bubble ${m.senderId===user?.id?"mine":""}`}>{m.body}<small>{new Date(m.createdAt).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><form className="chat-input" onSubmit={send}><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Votre message…"/><button>Envoyer</button></form></>:<div className="empty"><h3>Aucune conversation</h3></div>}</section></div>;
}

function Admin() {
  const [stats,setStats]=useState<any>(null); useEffect(()=>{api("/admin/dashboard").then(setStats)},[]);
  return <Layout><section className="admin-page"><AdminNav/><div className="admin-main"><div className="admin-heading"><div><span className="eyebrow">ADMINISTRATION</span><h1>Tableau de bord général</h1></div></div>{!stats?<Loading/>:<><div className="stat-grid"><Stat label="Événements actifs" value={stats.events}/><Stat label="Candidatures" value={stats.applications}/><Stat label="Revenus" value={money(stats.revenueCents)}/><Stat label="Signalements ouverts" value={stats.openReports}/></div><div className="admin-grid"><div className="panel chart"><div className="panel-title"><h2>Activité sur 30 jours</h2><span>Données de démonstration</span></div><div className="bars">{[32,50,42,68,60,82,75,94,70,85,97,88].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></div><div className="panel quick"><h2>Actions rapides</h2><Link to="/admin/applications">Traiter les candidatures <span>→</span></Link><Link to="/admin/scanner">Scanner un billet <span>→</span></Link><Link to="/events">Voir les événements <span>→</span></Link></div></div></>}</div></section></Layout>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><small>{label.toUpperCase()}</small><strong>{value}</strong><span>Mis à jour maintenant</span></div>}
function AdminNav(){return <aside className="admin-nav"><Logo/><NavLink end to="/admin">Vue générale</NavLink><NavLink to="/admin/applications">Candidatures</NavLink><NavLink to="/admin/scanner">Scanner les billets</NavLink><Link to="/events">Événements publics</Link></aside>}

function AdminApplications() {
  const [items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[message,setMessage]=useState(""); const load=()=>api<any[]>("/admin/applications").then(v=>{setItems(v);if(selected)setSelected(v.find(x=>x.id===selected.id))});useEffect(()=>{load()},[]);
  const decide=async(accept:boolean)=>{await api(`/admin/applications/${selected.id}/decision`,{method:"POST",body:JSON.stringify({accept,notes:"Décision prise depuis l’administration."})});setMessage(accept?"Candidature acceptée et réservation créée.":"Candidature refusée.");await load()};
  return <Layout><section className="admin-page"><AdminNav/><div className="admin-main"><span className="eyebrow">ADMINISTRATION</span><h1>Candidatures</h1>{message&&<Notice kind="success">{message}</Notice>}<div className="applications-layout"><div className="panel table"><div className="table-row head"><span>Candidat</span><span>Événement</span><span>Statut</span></div>{items.map(a=><button key={a.id} onClick={()=>setSelected(a)} className={`table-row ${selected?.id===a.id?"selected":""}`}><span><b>{a.user.displayName}</b><small>{a.user.profile?.city}</small></span><span>{a.event.title}</span><span>{a.status.replaceAll("_"," ")}</span></button>)}</div><aside className="panel candidate-detail">{selected?<><div className="avatar large">{selected.user.displayName.slice(0,2).toUpperCase()}</div><h2>{selected.user.displayName}</h2><p>{selected.user.profile?.profession} · {selected.user.profile?.city}</p><hr/><small>MOTIVATION</small><blockquote>{selected.motivation}</blockquote><small>CENTRES D’INTÉRÊT</small><div className="chips">{selected.user.profile?.interests.map((x:string)=><span key={x}>{x}</span>)}</div>{!["CONFIRMED","REFUSED","PAYMENT_PENDING"].includes(selected.status)&&<div className="decision-buttons"><button className="button" onClick={()=>decide(true)}>Accepter</button><button className="button danger" onClick={()=>decide(false)}>Refuser</button></div>}</>:<div className="empty"><h3>Sélectionnez une candidature</h3></div>}</aside></div></div></section></Layout>;
}

function Scanner() {
  const [code,setCode]=useState("NOUR-TICKET-DEMO-482"),[result,setResult]=useState<any>(null),[error,setError]=useState(""); const scan=async(e:FormEvent)=>{e.preventDefault();setResult(null);setError("");try{setResult(await api("/admin/tickets/scan",{method:"POST",body:JSON.stringify({code})}))}catch(err){setError((err as Error).message)}};
  return <Layout><section className="admin-page"><AdminNav/><div className="admin-main"><span className="eyebrow">ACCUEIL</span><h1>Scanner un billet</h1><div className="scanner-layout"><form className="scanner panel" onSubmit={scan}><div className="scan-frame"><i/><span>QR</span></div><label>Code du billet<input value={code} onChange={e=>setCode(e.target.value)}/></label><button className="button full">Vérifier et valider l’entrée</button></form><aside className={`scan-result panel ${result?"success":error?"error":""}`}>{result?<><b>✓</b><h2>Entrée autorisée</h2><p>{result.participant}</p><span>{result.event}</span></>:error?<><b>×</b><h2>Entrée refusée</h2><p>{error}</p></>:<><b>⌗</b><h2>En attente d’un billet</h2><p>Scannez ou saisissez le code.</p></>}</aside></div></div></section></Layout>;
}

export function App(){return <AuthProvider><Routes><Route path="/" element={<Home/>}/><Route path="/events" element={<Events/>}/><Route path="/events/:id" element={<EventDetail/>}/><Route path="/login" element={<Login/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/admin" element={<Protected roles={["ADMIN","ORGANIZER","MODERATOR","RECEPTION"]}><Admin/></Protected>}/><Route path="/admin/applications" element={<Protected roles={["ADMIN","ORGANIZER"]}><AdminApplications/></Protected>}/><Route path="/admin/scanner" element={<Protected roles={["ADMIN","ORGANIZER","RECEPTION"]}><Scanner/></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></AuthProvider>}
