-- DataMigration: nouvelle architecture éditoriale (instructions définitives 2026-09-20) —
-- couvre explicitement rencontres amoureuses, amitié, solitude et networking professionnel.
-- Recatégorise les 10 articles déjà rédigés (aucun supprimé) et ajoute 2 nouveaux articles
-- (amitié, networking professionnel) en fin de file, avec image et lien interne pertinent.
UPDATE "Article" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'speed-dating-paris-premiere-soiree-sans-pression';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'rencontrer-quelquun-apres-35-ans-changer-de-methode';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'raviver-complicite-couple-installe';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'sortir-en-couple-multiplier-premieres-fois';
UPDATE "ArticleQueueEntry" SET "category" = 'Solitude et vie sociale' WHERE "slug" = 'sortir-solitude-choisie-premier-pas';
UPDATE "ArticleQueueEntry" SET "category" = 'Solitude et vie sociale' WHERE "slug" = 'vivre-seul-sans-isolement-reseau-apres-rupture';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'avant-le-mariage-questions-a-se-poser-a-deux';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'ecoute-active-competence-sous-estimee-premier-rendez-vous';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'dire-non-sans-blesser-poser-ses-limites';
UPDATE "ArticleQueueEntry" SET "category" = 'Rencontres amoureuses' WHERE "slug" = 'rythme-relationnel-pas-de-bon-tempo-universel';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") VALUES (gen_random_uuid()::text, 10, 'Se faire de vrais amis à l''âge adulte : pourquoi c''est plus dur, et comment y remédier', 'se-faire-des-amis-adulte', 'Passé un certain âge, les amitiés ne se forment plus par hasard à la sortie des cours. Voici pourquoi, et ce qui fonctionne réellement pour en recréer.', 'À l''école ou pendant les études, l''amitié se formait presque sans effort : les mêmes personnes, chaque jour, au même endroit, pendant des années. Cette répétition involontaire — ce que les chercheurs appellent parfois « la proximité répétée » — est le principal moteur de la plupart des amitiés durables. Une fois dans la vie active, ce mécanisme disparaît presque entièrement : les collègues changent, les horaires ne se recoupent plus, et la proximité répétée qui créait des amitiés sans qu''on y pense ne se produit plus toute seule.

Ce n''est donc pas que les adultes deviennent moins sociables avec l''âge. C''est que l''environnement qui produisait des amitiés automatiquement a disparu, et que personne ne nous a appris à le remplacer volontairement. D''où cette impression fréquente, passé 30 ou 40 ans, d''avoir un cercle social qui se réduit sans qu''on ait rien fait de mal.

La solution la plus fiable consiste à recréer artificiellement cette proximité répétée : fréquenter régulièrement le même type d''endroit, avec les mêmes personnes ou un groupe suffisamment stable, plutôt que de multiplier les rencontres isolées et sans suite. Une amitié se construit rarement en une seule soirée réussie ; elle se construit en se recroisant plusieurs fois, dans un cadre qui donne une bonne raison de recommencer.

C''est précisément ce que permettent des événements réguliers pensés pour la rencontre, au-delà du cadre strictement romantique : ils offrent un prétexte simple et récurrent pour revoir des visages qu''on a déjà croisés, sans avoir à organiser soi-même chaque fois quelque chose de nouveau. Ce n''est pas différent, dans son mécanisme, de ce qui fonctionnait à l''école — seulement recréé volontairement, une fois que la vie ne le fait plus pour nous.

Envie de recréer cette proximité régulière ? [Découvrez nos prochains événements](/events) pour commencer, sans pression, avec des personnes qui font la même démarche que vous.', 'Amitié', ARRAY['amitié','se faire des amis adulte','isolement social','vie sociale']::text[], 'Se faire de vrais amis à l''âge adulte', 'Pourquoi les amitiés adultes ne se forment plus par hasard, et comment recréer volontairement les conditions qui les faisaient naître plus jeune.', '/static/defaults/auth-terrace.jpg', CURRENT_TIMESTAMP);
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") VALUES (gen_random_uuid()::text, 11, 'Réseauter sans se forcer : ce qui fait vraiment fonctionner une soirée networking', 'reseauter-sans-se-forcer-soiree-networking', 'Le networking a mauvaise réputation parce qu''on l''imagine intéressé et artificiel. Bien fait, c''est l''inverse : une conversation sincère qui, accessoirement, ouvre des portes.', 'Le mot « networking » évoque souvent une image précise et peu engageante : un groupe de personnes en costume qui échangent des cartes de visite en surveillant qui est le plus utile à connaître dans la salle. Cette image explique pourquoi tant de gens évitent ces soirées, alors même qu''elles restent l''un des moyens les plus efficaces de faire évoluer une carrière, changer de secteur ou simplement rencontrer des personnes qui comprennent son métier.

Le networking qui fonctionne réellement ressemble très peu à cette image. Les personnes qui en retirent le plus ne sont pas celles qui distribuent le plus de cartes, mais celles qui engagent quelques conversations un peu plus longues, avec une curiosité sincère pour ce que fait l''autre, sans calcul immédiat sur l''utilité de l''échange. Paradoxalement, c''est cette absence de calcul apparent qui rend la conversation agréable pour les deux parties — et donc plus mémorable qu''un échange purement transactionnel.

Une bonne préparation ne consiste pas à répéter un discours de présentation parfait, mais à préparer deux ou trois questions sincères sur ce que font les autres : quel projet les occupe actuellement, ce qui les a menés à leur poste, ce qu''ils changeraient dans leur secteur. Ces questions ouvrent des conversations bien plus riches qu''un simple échange de titres et d''entreprises.

Le suivi compte autant que la soirée elle-même : un message bref envoyé dans les jours qui suivent, qui rappelle un détail précis de la conversation, transforme une rencontre agréable en relation professionnelle qui dure. La plupart des occasions de networking se perdent non pas pendant la soirée, mais dans l''absence totale de suivi après.

Pour progresser sans se forcer, autant choisir un cadre déjà pensé pour ce type d''échange plutôt qu''une conférence impersonnelle : [découvrez nos prochaines soirées networking](/events?category=Networking), pensées pour des conversations qui comptent, pas pour collectionner des cartes de visite.', 'Networking professionnel', ARRAY['networking','réseau professionnel','soirée networking','carrière']::text[], 'Réseauter sans se forcer : ce qui fait vraiment fonctionner une soirée networking', 'Le networking efficace ressemble peu à l''image qu''on en a. Ce qui fait vraiment la différence : la sincérité de la conversation et la qualité du suivi.', '/static/defaults/networking.jpg', CURRENT_TIMESTAMP);