-- DataMigration: annule la migration 20260920050000 — le propriétaire confirme vouloir
-- conserver le principe d'un article proposé par jour (jamais tous en même temps), contredisant
-- l'ordre correctif précédent. Renvoie les 9 articles encore DRAFT (hors celui déjà publié) vers
-- ArticleQueueEntry dans le même ordre qu'avant, réinitialise ArticleQueueState.
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 1, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'raviver-complicite-couple-installe';
DELETE FROM "Article" WHERE "slug" = 'raviver-complicite-couple-installe';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 2, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'sortir-solitude-choisie-premier-pas';
DELETE FROM "Article" WHERE "slug" = 'sortir-solitude-choisie-premier-pas';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 3, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'avant-le-mariage-questions-a-se-poser-a-deux';
DELETE FROM "Article" WHERE "slug" = 'avant-le-mariage-questions-a-se-poser-a-deux';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 4, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'ecoute-active-competence-sous-estimee-premier-rendez-vous';
DELETE FROM "Article" WHERE "slug" = 'ecoute-active-competence-sous-estimee-premier-rendez-vous';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 5, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'rythme-relationnel-pas-de-bon-tempo-universel';
DELETE FROM "Article" WHERE "slug" = 'rythme-relationnel-pas-de-bon-tempo-universel';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 6, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'rencontrer-quelquun-apres-35-ans-changer-de-methode';
DELETE FROM "Article" WHERE "slug" = 'rencontrer-quelquun-apres-35-ans-changer-de-methode';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 7, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'sortir-en-couple-multiplier-premieres-fois';
DELETE FROM "Article" WHERE "slug" = 'sortir-en-couple-multiplier-premieres-fois';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 8, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'vivre-seul-sans-isolement-reseau-apres-rupture';
DELETE FROM "Article" WHERE "slug" = 'vivre-seul-sans-isolement-reseau-apres-rupture';
INSERT INTO "ArticleQueueEntry" ("id","position","title","slug","excerpt","content","category","keywords","metaTitle","metaDescription","imageUrl","createdAt") SELECT gen_random_uuid()::text, 9, "title","slug",COALESCE("excerpt",''),"content","category","keywords",COALESCE("metaTitle",''),COALESCE("metaDescription",''),"imageUrl",CURRENT_TIMESTAMP FROM "Article" WHERE "slug" = 'dire-non-sans-blesser-poser-ses-limites';
DELETE FROM "Article" WHERE "slug" = 'dire-non-sans-blesser-poser-ses-limites';
UPDATE "ArticleQueueState" SET "lastReleasedAt" = CURRENT_TIMESTAMP WHERE "id" = 'singleton';